#!/usr/bin/env node
'use strict';

/* Fail closed before story design: rank evidence -> benchmark pool -> breakdown -> matrix -> Book DNA. */
const fs = require('fs'); const path = require('path'); const { CliError, emitError } = require('./cap-utils'); const bookDna = require('./book-dna'); const deepBreakdown = require('./deep-breakdown-gate');
const RANKING = 'analysis/ranking-snapshot.json'; const POOL = 'evidence/derivations/benchmark-pool.md'; const BREAKDOWN = 'analysis/breakdown.md'; const MATRIX = 'evidence/derivations/benchmark-feature-matrix.md'; const BOUNDARIES = 'evidence/derivations/source-boundaries.md';
function argsOf(argv) { const out = {}; for (let i = 0; i < argv.length; i++) { const v = argv[i]; if (v.startsWith('--')) { const n = argv[i + 1]; out[v.slice(2)] = n && !n.startsWith('--') ? n : true; if (out[v.slice(2)] !== true) i++; } else if (!out.command) out.command = v; else if (!out.project) out.project = v; } return out; }
function projectOf(input) { const project = path.resolve(input || ''); if (!input || !fs.existsSync(path.join(project, 'state', 'project-state.json'))) throw new CliError('STATE_MISSING', 'Missing state/project-state.json', { project }); return project; }
function activeRows(text) { return text.split(/\r?\n/).filter((line) => /^\s*\|/.test(line) && !/^\s*\|?\s*[-:| ]+\|\s*$/.test(line)).filter((line) => /\b(adopted|selected|active|入选|采纳)\b/i.test(line)); }
function validate(projectInput) { const project = projectOf(projectInput); const errors = []; const details = {}; const rank = path.join(project, RANKING); if (!fs.existsSync(rank)) errors.push('RANKING_SNAPSHOT_MISSING'); else { try { const data = JSON.parse(fs.readFileSync(rank, 'utf8')); details.ranking_items = Array.isArray(data.items) ? data.items.length : 0; if (details.ranking_items < 10) errors.push('RANKING_SAMPLE_TOO_SMALL'); if (!data.captured_at || !data.acquisition) errors.push('RANKING_PROVENANCE_MISSING'); const decoder = data.acquisition?.font_decoder || {}; details.ranking_font_low_confidence = Number(decoder.low_confidence_count || 0); details.ranking_font_warnings = Array.isArray(decoder.warnings) ? decoder.warnings.length : 0; if (details.ranking_font_warnings && decoder.warnings.some((item) => /FONT_DECODE_(?:FAILED|DEPENDENCY_MISSING|FONT_URL_MISSING)/i.test(String(item)))) errors.push('RANKING_FONT_DECODER_FAILED'); if (data.items?.some((item) => /[\uE000-\uF8FF]/.test(`${item.title || ''}${item.author || ''}${item.blurb || ''}`))) errors.push('RANKING_TEXT_UNREADABLE'); } catch (_) { errors.push('RANKING_SNAPSHOT_INVALID'); } }
  for (const relative of [POOL, BREAKDOWN, MATRIX, BOUNDARIES]) if (!fs.existsSync(path.join(project, relative))) errors.push(`MISSING_${path.basename(relative).replace(/[^A-Za-z0-9]/g, '_').toUpperCase()}`);
  if (fs.existsSync(path.join(project, POOL))) { details.benchmark_rows = activeRows(fs.readFileSync(path.join(project, POOL), 'utf8')).length; if (details.benchmark_rows < 10) errors.push('BENCHMARK_POOL_TOO_SMALL'); }
  const depth = deepBreakdown.validate(project); details.deep_breakdown = depth.details; for (const finding of depth.errors) errors.push(finding.code || String(finding));
  if (fs.existsSync(path.join(project, BREAKDOWN))) { details.breakdown_chars = fs.readFileSync(path.join(project, BREAKDOWN), 'utf8').trim().length; if (details.breakdown_chars < 500) errors.push('BREAKDOWN_TOO_THIN'); }
  let compiled = null; if (!errors.some((code) => code.startsWith('MISSING_'))) { compiled = bookDna.compile(project); details.book_dna_mechanisms = compiled.mechanism_count; details.book_dna_dimensions = compiled.dimension_count; if (compiled.mechanism_count < 6) errors.push('BOOK_DNA_TOO_THIN'); if (compiled.dimension_count < 3) errors.push('BOOK_DNA_DIMENSIONS_TOO_NARROW'); }
  if (errors.length) throw new CliError('PREPRODUCTION_GATE_FAILED', 'Required market-to-Book-DNA chain is incomplete', { errors, details }); return { ok: true, project, ranking: RANKING, pool: POOL, breakdown: BREAKDOWN, matrix: MATRIX, book_dna: bookDna.OUTPUT, details }; }
function run(argv = process.argv.slice(2)) { const args = argsOf(argv); const project = args.project || (args.command && args.command !== 'validate' ? args.command : null); if (!project) throw new CliError('USAGE', 'Usage: node preproduction-gate.js validate <PROJECT>'); const report = validate(project); process.stdout.write(`${JSON.stringify(report, null, 2)}\n`); return report; }
if (require.main === module) { try { run(); } catch (error) { process.exitCode = emitError(error, 'preproduction-gate'); } }
module.exports = { RANKING, POOL, BREAKDOWN, MATRIX, BOUNDARIES, activeRows, validate, run };
